# Generated by Django 5.2.4 on 2025-09-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
