# Generated by Django 5.2.4 on 2025-09-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_leaverequest_admin_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick leave', 'Sick Leave'), ('casual leave', 'Casual Leave'), ('vacation', 'Vacation'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('Rejected', 'rejected')], default='Pending', max_length=20),
        ),
    ]
