# Generated by Django 5.2.4 on 2025-10-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_leaverequest_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_face_data',
            field=models.BooleanField(default=False),
        ),
    ]
