# Generated by Django 5.2.4 on 2025-10-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_facechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Checked In', 'Checked In (No Check-Out)')], default='Absent', max_length=20),
        ),
    ]
