# Generated by Django 5.2.4 on 2025-10-15 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick leave', 'Sick Leave'), ('casual leave', 'Casual Leave'), ('vacation', 'Vacation'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Checked In', 'Checked In (No Check-Out)'), ('Holiday', 'Holiday'), ('Leave', 'Leave')], default='Absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick leave', 'Sick Leave'), ('casual leave', 'Casual Leave'), ('vacation', 'Vacation'), ('emergency', 'Emergency'), ('other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
